### ISSUE TITLE
MySQL2::Error exception when running update_all

### ISSUE THREAD

**Issue by mb-dev** [taskrabbit/makara#12]
I am experiencing this MySQL2::Error with error number 0 when running update_all query.

Model.update_all(['field =?', value], ['field = ?', value])

I am getting:

```
rake aborted!

/Users/moshebergman/.rvm/gems/ruby-1.9.3-p327@ewok/gems/activerecord-3.2.13/lib/active_record/connection_adapters/mysql2_adapter.rb:239:in `affected_rows'
/Users/moshebergman/.rvm/gems/ruby-1.9.3-p327@ewok/gems/activerecord-3.2.13/lib/active_record/connection_adapters/mysql2_adapter.rb:239:in `exec_delete'
/Users/moshebergman/.rvm/gems/ruby-1.9.3-p327@ewok/gems/activerecord-3.2.13/lib/active_record/connection_adapters/abstract/database_statements.rb:96:in `update'
/Users/moshebergman/.rvm/gems/ruby-1.9.3-p327@ewok/gems/activerecord-3.2.13/lib/active_record/connection_adapters/abstract/query_cache.rb:14:in `update'
/Users/moshebergman/.rvm/gems/ruby-1.9.3-p327@ewok/bundler/gems/makara-05bc94ff1c6e/lib/active_record/connection_adapters/makara_adapter.rb:139:in `update'
/Users/moshebergman/.rvm/gems/ruby-1.9.3-p327@ewok/bundler/gems/makara-05bc94ff1c6e/lib/active_record/connection_adapters/makara_adapter.rb:142:in `method_missing'
/Users/moshebergman/.rvm/gems/ruby-1.9.3-p327@ewok/gems/activerecord-3.2.13/lib/active_record/relation.rb:294:in `update_all'
/Users/moshebergman/.rvm/gems/ruby-1.9.3-p327@ewok/gems/activerecord-3.2.13/lib/active_record/relation.rb:278:in `update_all'
/Users/moshebergman/.rvm/gems/ruby-1.9.3-p327@ewok/gems/activerecord-3.2.13/lib/active_record/querying.rb:7:in `update_all'
```

Switching to mysql2 adapter and things are working fine. So I wonder what can be the issue. This is with makara from the date "Jan 29, 2013", I will try updating to the latest version.

**Comment by mb-dev** [comment]
With the latest version things are working fine. So i'll see if I can update. Sorry about that!

**Comment by mb-dev** [comment]
After some more digging, it's also related to issue #6
