### ISSUE TITLE
Disconnecting a read slave halts the entire application

### ISSUE THREAD

**Issue by donaldpiret** [taskrabbit/makara#16]
It was my understanding that Makara should automatically deal with read slaves that become unavailable?
However when testing this (after it happened once in our production environment), our application actually throws the following:

Mysql2::Error: Unknown MySQL server host

Full stack trace:

```
mysql2 (0.3.13) lib/mysql2/client.rb:58:in `connect'
mysql2 (0.3.13) lib/mysql2/client.rb:58:in `initialize'
/home/deploy/.bundler/roomorama_staging/ruby/2.0.0/bundler/gems/rails-59a35610459d/activerecord/lib/active_record/connection_adapters/mysql2_adapter.rb:16:in `new'
/home/deploy/.bundler/roomorama_staging/ruby/2.0.0/bundler/gems/rails-59a35610459d/activerecord/lib/active_record/connection_adapters/mysql2_adapter.rb:16:in `mysql2_connection'
/home/deploy/.bundler/roomorama_staging/ruby/2.0.0/bundler/gems/makara-73ade49da3bc/lib/active_record/connection_adapters/makara_adapter.rb:31:in `underlying_connection_for'
/home/deploy/.bundler/roomorama_staging/ruby/2.0.0/bundler/gems/makara-73ade49da3bc/lib/active_record/connection_adapters/makara_adapter.rb:7:in `block in makara_connection'
/home/deploy/.bundler/roomorama_staging/ruby/2.0.0/bundler/gems/makara-73ade49da3bc/lib/makara/config_parser.rb:19:in `block in each_config'
/home/deploy/.bundler/roomorama_staging/ruby/2.0.0/bundler/gems/makara-73ade49da3bc/lib/makara/config_parser.rb:13:in `map'
/home/deploy/.bundler/roomorama_staging/ruby/2.0.0/bundler/gems/makara-73ade49da3bc/lib/makara/config_parser.rb:13:in `each_config'
/home/deploy/.bundler/roomorama_staging/ruby/2.0.0/bundler/gems/makara-73ade49da3bc/lib/active_record/connection_adapters/makara_adapter.rb:6:in `makara_connection'
/home/deploy/.bundler/roomorama_staging/ruby/2.0.0/bundler/gems/makara-73ade49da3bc/lib/active_record/connection_adapters/makara_mysql2_adapter.rb:7:in `makara_mysql2_connection'
/home/deploy/.bundler/roomorama_staging/ruby/2.0.0/bundler/gems/rails-59a35610459d/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb:315:in `new_connection'
/home/deploy/.bundler/roomorama_staging/ruby/2.0.0/bundler/gems/rails-59a35610459d/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb:325:in `checkout_new_connection'
/home/deploy/.bundler/roomorama_staging/ruby/2.0.0/bundler/gems/rails-59a35610459d/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb:247:in `block (2 levels) in checkout'
/home/deploy/.bundler/roomorama_staging/ruby/2.0.0/bundler/gems/rails-59a35610459d/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb:242:in `loop'
/home/deploy/.bundler/roomorama_staging/ruby/2.0.0/bundler/gems/rails-59a35610459d/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb:242:in `block in checkout'
/usr/local/lib/ruby/2.0.0/monitor.rb:211:in `mon_synchronize'
/home/deploy/.bundler/roomorama_staging/ruby/2.0.0/bundler/gems/rails-59a35610459d/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb:239:in `checkout'
/home/deploy/.bundler/roomorama_staging/ruby/2.0.0/bundler/gems/rails-59a35610459d/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb:102:in `block in connection'
/usr/local/lib/ruby/2.0.0/monitor.rb:211:in `mon_synchronize'
/home/deploy/.bundler/roomorama_staging/ruby/2.0.0/bundler/gems/rails-59a35610459d/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb:101:in `connection'
/home/deploy/.bundler/roomorama_staging/ruby/2.0.0/bundler/gems/rails-59a35610459d/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb:410:in `retrieve_connection'
/home/deploy/.bundler/roomorama_staging/ruby/2.0.0/bundler/gems/rails-59a35610459d/activerecord/lib/active_record/connection_adapters/abstract/connection_specification.rb:171:in `retrieve_connection'
/home/deploy/.bundler/roomorama_staging/ruby/2.0.0/bundler/gems/rails-59a35610459d/activerecord/lib/active_record/connection_adapters/abstract/connection_specification.rb:145:in `connection'
/home/deploy/.bundler/roomorama_staging/ruby/2.0.0/bundler/gems/rails-59a35610459d/activerecord/lib/active_record/query_cache.rb:67:in `rescue in call'
/home/deploy/.bundler/roomorama_staging/ruby/2.0.0/bundler/gems/rails-59a35610459d/activerecord/lib/active_record/query_cache.rb:61:in `call'
/home/deploy/.bundler/roomorama_staging/ruby/2.0.0/bundler/gems/rails-59a35610459d/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call'
/home/deploy/.bundler/roomorama_staging/ruby/2.0.0/bundler/gems/rails-59a35610459d/actionpack/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
/home/deploy/.bundler/roomorama_staging/ruby/2.0.0/bundler/gems/rails-59a35610459d/activesupport/lib/active_support/callbacks.rb:405:in `_run__2937628382615234653__call__2629546183784262930__callbacks'
/home/deploy/.bundler/roomorama_staging/ruby/2.0.0/bundler/gems/rails-59a35610459d/activesupport/lib/active_support/callbacks.rb:405:in `__run_callback'
/home/deploy/.bundler/roomorama_staging/ruby/2.0.0/bundler/gems/rails-59a35610459d/activesupport/lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
/home/deploy/.bundler/roomorama_staging/ruby/2.0.0/bundler/gems/rails-59a35610459d/activesupport/lib/active_support/callbacks.rb:81:in `run_callbacks'
/home/deploy/.bundler/roomorama_staging/ruby/2.0.0/bundler/gems/rails-59a35610459d/actionpack/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
rack (1.4.5) lib/rack/sendfile.rb:102:in `call'
/home/deploy/.bundler/roomorama_staging/ruby/2.0.0/bundler/gems/rails-59a35610459d/actionpack/lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
airbrake (3.1.12) lib/airbrake/rails/middleware.rb:13:in `call'
/home/deploy/.bundler/roomorama_staging/ruby/2.0.0/bundler/gems/rails-59a35610459d/actionpack/lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
/home/deploy/.bundler/roomorama_staging/ruby/2.0.0/bundler/gems/rails-59a35610459d/actionpack/lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
/home/deploy/.bundler/roomorama_staging/ruby/2.0.0/bundler/gems/rails-59a35610459d/railties/lib/rails/rack/logger.rb:32:in `call_app'
/home/deploy/.bundler/roomorama_staging/ruby/2.0.0/bundler/gems/rails-59a35610459d/railties/lib/rails/rack/logger.rb:16:in `block in call'
/home/deploy/.bundler/roomorama_staging/ruby/2.0.0/bundler/gems/rails-59a35610459d/activesupport/lib/active_support/tagged_logging.rb:22:in `tagged'
/home/deploy/.bundler/roomorama_staging/ruby/2.0.0/bundler/gems/rails-59a35610459d/railties/lib/rails/rack/logger.rb:16:in `call'
/home/deploy/.bundler/roomorama_staging/ruby/2.0.0/bundler/gems/rails-59a35610459d/actionpack/lib/action_dispatch/middleware/request_id.rb:22:in `call'
app/middleware/utf_url_middleware.rb:10:in `call'
rack (1.4.5) lib/rack/methodoverride.rb:21:in `call'
rack (1.4.5) lib/rack/runtime.rb:17:in `call'
/home/deploy/.bundler/roomorama_staging/ruby/2.0.0/bundler/gems/rails-59a35610459d/activesupport/lib/active_support/cache/strategy/local_cache.rb:72:in `call'
/home/deploy/.bundler/roomorama_staging/ruby/2.0.0/bundler/gems/rack-throttle-3706324225c5/lib/rack/throttle/limiter.rb:34:in `call'
app/middleware/api_defender.rb:38:in `call'
rack (1.4.5) lib/rack/lock.rb:15:in `call'
rack-ssl (1.3.3) lib/rack/ssl.rb:27:in `call'
rack-cache (1.2) lib/rack/cache/context.rb:136:in `forward'
rack-cache (1.2) lib/rack/cache/context.rb:245:in `fetch'
rack-cache (1.2) lib/rack/cache/context.rb:185:in `lookup'
rack-cache (1.2) lib/rack/cache/context.rb:66:in `call!'
rack-cache (1.2) lib/rack/cache/context.rb:51:in `call'
airbrake (3.1.12) lib/airbrake/user_informer.rb:16:in `_call'
airbrake (3.1.12) lib/airbrake/user_informer.rb:12:in `call'
/home/deploy/.bundler/roomorama_staging/ruby/2.0.0/bundler/gems/rails-59a35610459d/railties/lib/rails/engine.rb:484:in `call'
/home/deploy/.bundler/roomorama_staging/ruby/2.0.0/bundler/gems/rails-59a35610459d/railties/lib/rails/application.rb:231:in `call'
/home/deploy/.bundler/roomorama_staging/ruby/2.0.0/bundler/gems/rails-59a35610459d/railties/lib/rails/railtie/configurable.rb:30:in `method_missing'
unicorn (4.6.3) lib/unicorn/http_server.rb:552:in `process_client'
unicorn (4.6.3) lib/unicorn/http_server.rb:632:in `worker_loop'
newrelic_rpm (3.6.1.88) lib/new_relic/agent/instrumentation/unicorn_instrumentation.rb:22:in `call'
newrelic_rpm (3.6.1.88) lib/new_relic/agent/instrumentation/unicorn_instrumentation.rb:22:in `block (4 levels) in <top (required)>'
unicorn (4.6.3) lib/unicorn/http_server.rb:500:in `spawn_missing_workers'
unicorn (4.6.3) lib/unicorn/http_server.rb:511:in `maintain_worker_count'
unicorn (4.6.3) lib/unicorn/http_server.rb:277:in `join'
unicorn (4.6.3) bin/unicorn_rails:209:in `<top (required)>'
/home/deploy/.bundler/roomorama_staging/ruby/2.0.0/bin/unicorn_rails:23:in `load'
/home/deploy/.bundler/roomorama_staging/ruby/2.0.0/bin/unicorn_rails:23:in `<main>'
```

**Comment by mnelson** [comment]
Looks like this was happening on startup. The `underlying_connection_for` only occurs upon initialization of the adapter.

```
/home/deploy/.bundler/roomorama_staging/ruby/2.0.0/bundler/gems/makara-73ade49da3bc/lib/active_record/connection_adapters/makara_adapter.rb:31:in `underlying_connection_for'
```

**Comment by donaldpiret** [comment]
Is there a way these exceptions can be rescued for read slaves only? This seemed to be an issue when our unicorn instances were restarting.

**Comment by mnelson** [comment]
IMO this is app-specific error handling. It's expected that a connection would initially be made. There's likely a spot in your after_fork which you reconnect and handle these errors.
