### ISSUE TITLE
Can't create a error matcher for  Mysql2::Error

### ISSUE THREAD

**Issue by guiocavalcanti** [taskrabbit/makara#98]
Hey there! I'm trying to use makara with Rails in order to make my application more resilient to read replica errors. I'm using `connection_error_matchers` configuration like this:

```yaml
staging:
  # ...
  makara:
    connection_error_matchers:
      - "Mysql2::Error: Lost connection to MySQL server at 'reading initial communication packet', system error: 0"
    connections:
      - role: master
        host: # ...
        name: core-staging-1086:db01
      - role: slave
        host: # ...
        name: core-staging-1086:db01-replica
      - role: slave
        host: # ...
        name: core-staging-1086:db01-replica-2
```

When I intentionally restart a the read replicas and refresh some application page, I still get the errors in the log:

```
Mysql2::Error (Lost connection to MySQL server at 'reading initial communication packet', system error: 0):
  mysql2 (0.3.16) lib/mysql2/client.rb:70:in `connect'
  mysql2 (0.3.16) lib/mysql2/client.rb:70:in `initialize'
  activerecord (4.1.13) lib/active_record/connection_adapters/mysql2_adapter.rb:18:in `new'
  activerecord (4.1.13) lib/active_record/connection_adapters/mysql2_adapter.rb:18:in `mysql2_connection'
  makara (0.3.0.rc3) lib/active_record/connection_adapters/mysql2_makara_adapter.rb:39:in `active_record_connection_for'
  makara (0.3.0.rc3) lib/active_record/connection_adapters/makara_abstract_adapter.rb:187:in `connection_for'
  makara (0.3.0.rc3) lib/makara/proxy.rb:215:in `block (2 levels) in instantiate_connections'
  makara (0.3.0.rc3) lib/makara/pool.rb:39:in `add'
  makara (0.3.0.rc3) lib/makara/proxy.rb:214:in `block in instantiate_connections'
  makara (0.3.0.rc3) lib/makara/proxy.rb:213:in `each'
  makara (0.3.0.rc3) lib/makara/proxy.rb:213:in `instantiate_connections'
  makara (0.3.0.rc3) lib/makara/proxy.rb:51:in `initialize'
  makara (0.3.0.rc3) lib/active_record/connection_adapters/makara_abstract_adapter.rb:131:in `initialize'
  makara (0.3.0.rc3) lib/active_record/connection_adapters/mysql2_makara_adapter.rb:9:in `new'
  makara (0.3.0.rc3) lib/active_record/connection_adapters/mysql2_makara_adapter.rb:9:in `mysql2_makara_connection'
  activerecord (4.1.13) lib/active_record/connection_adapters/abstract/connection_pool.rb:435:in `new_connection'
  activerecord (4.1.13) lib/active_record/connection_adapters/abstract/connection_pool.rb:445:in `checkout_new_connection'
  activerecord (4.1.13) lib/active_record/connection_adapters/abstract/connection_pool.rb:416:in `acquire_connection'
  activerecord (4.1.13) lib/active_record/connection_adapters/abstract/connection_pool.rb:351:in `block in checkout'
  /usr/local/rubies/2.0.0-p247/lib/ruby/2.0.0/monitor.rb:211:in `mon_synchronize'
  activerecord (4.1.13) lib/active_record/connection_adapters/abstract/connection_pool.rb:350:in `checkout'
  activerecord (4.1.13) lib/active_record/connection_adapters/abstract/connection_pool.rb:265:in `block in connection'
  /usr/local/rubies/2.0.0-p247/lib/ruby/2.0.0/monitor.rb:211:in `mon_synchronize'
  activerecord (4.1.13) lib/active_record/connection_adapters/abstract/connection_pool.rb:264:in `connection'
  activerecord (4.1.13) lib/active_record/connection_adapters/abstract/connection_pool.rb:541:in `retrieve_connection'
  activerecord (4.1.13) lib/active_record/connection_handling.rb:113:in `retrieve_connection'
  activerecord (4.1.13) lib/active_record/connection_handling.rb:87:in `connection'
  activerecord (4.1.13) lib/active_record/query_cache.rb:51:in `restore_query_cache_settings'
  activerecord (4.1.13) lib/active_record/query_cache.rb:43:in `rescue in call'
  activerecord (4.1.13) lib/active_record/query_cache.rb:32:in `call'
  newrelic_rpm (3.9.6.257) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  activerecord (4.1.13) lib/active_record/connection_adapters/abstract/connection_pool.rb:621:in `call'
  newrelic_rpm (3.9.6.257) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  actionpack (4.1.13) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.1.13) lib/active_support/callbacks.rb:82:in `run_callbacks'
  actionpack (4.1.13) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  newrelic_rpm (3.9.6.257) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  actionpack (4.1.13) lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
  newrelic_rpm (3.9.6.257) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  actionpack (4.1.13) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  newrelic_rpm (3.9.6.257) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  actionpack (4.1.13) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  newrelic_rpm (3.9.6.257) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  lograge (0.3.1) lib/lograge/rails_ext/rack/logger.rb:15:in `call_app'
  railties (4.1.13) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.1.13) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.1.13) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.1.13) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.1.13) lib/rails/rack/logger.rb:20:in `call'
  newrelic_rpm (3.9.6.257) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  request_store (1.1.0) lib/request_store/middleware.rb:8:in `call'
  newrelic_rpm (3.9.6.257) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  actionpack (4.1.13) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  newrelic_rpm (3.9.6.257) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  rack (1.5.5) lib/rack/methodoverride.rb:21:in `call'
  newrelic_rpm (3.9.6.257) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  rack (1.5.5) lib/rack/runtime.rb:17:in `call'
  newrelic_rpm (3.9.6.257) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  activesupport (4.1.13) lib/active_support/cache/strategy/local_cache_middleware.rb:26:in `call'
  newrelic_rpm (3.9.6.257) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  actionpack (4.1.13) lib/action_dispatch/middleware/static.rb:84:in `call'
  newrelic_rpm (3.9.6.257) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  rack (1.5.5) lib/rack/sendfile.rb:112:in `call'
  newrelic_rpm (3.9.6.257) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  rack-cors (0.4.0) lib/rack/cors.rb:80:in `call'
  newrelic_rpm (3.9.6.257) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  railties (4.1.13) lib/rails/engine.rb:514:in `call'
  railties (4.1.13) lib/rails/application.rb:144:in `call'
  newrelic_rpm (3.9.6.257) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  unicorn (4.8.3) lib/unicorn/http_server.rb:576:in `process_client'
  unicorn (4.8.3) lib/unicorn/http_server.rb:670:in `worker_loop'
  unicorn (4.8.3) lib/unicorn/http_server.rb:525:in `spawn_missing_workers'
  unicorn (4.8.3) lib/unicorn/http_server.rb:140:in `start'
  unicorn (4.8.3) bin/unicorn_rails:209:in `<top (required)>'
  /mnt/trustvox-staging/shared/bundle/ruby/2.0.0/bin/unicorn_rails:23:in `load'
  /mnt/trustvox-staging/shared/bundle/ruby/2.0.0/bin/unicorn_rails:23:in `<main>'
```

**Comment by evantahler** [comment]
I _think_ you just want something like this:

``` yaml
staging:
  # ...
  makara:
    connection_error_matchers:
      - \Lost connection to MySQL server\
```

**Comment by guiocavalcanti** [comment]
Hey @evantahler, same error =/

I'm diving into the code and I THINK this error happens while trying to establish database connection (`Proxy#instantiate_connections`). Is this method "protected" by the `ErrorHandler`?

**Comment by guiocavalcanti** [comment]
Maybe this is a replica of #92

**Comment by guiocavalcanti** [comment]
Hey @evantahler, should I work on a PR for this problem? I saw there are a couple of opened PRs and I'm not sure you are accepting contributions.

**Comment by evantahler** [comment]
Please do!

**Comment by bleonard** [comment]
I'm actively trying to help people fix issues for this gem. If you are using makara and still seeing this issue, please reopen the issue with a copy fox our database.yml and updated information. Ideally, you would have a test case that's failing in the specs - say it raises that error and it is not handled as expected.
